name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  intl: ^0.19.0
  fl_chart: ^0.68.0
  image_picker: ^1.1.0
  flutter_blue_plus: ^1.15.9
  permission_handler: ^11.3.1
  wifi_iot: ^0.3.17
  wifi_scan: ^0.4.0
  audioplayers: ^5.2.1
  http: ^1.2.1
  file_picker: ^8.0.0+1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sleeping.png
    - assets/hunger.png
    - assets/pain.png
    - assets/discomfort.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/LOGO.png"
